name: Skaffold
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci.yml
      - action.yml
jobs:
  build:
    name: Skaffold Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run Skaffold pipeline as command
        uses: bennovw/github-action-skaffold@latest
        id: build
        with:
          command: build
          working-directory: test
          skip-tests: false
          repository: ${{ secrets.SKAFFOLD_DEFAULT_REPO }}

      - name: Run Skaffold with output to JSON
        uses: bennovw/github-action-skaffold@latest
        with:
          command: build
          file-output: tags.json
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          working-directory: test

      - name: Read JSON file output
        run: cat tags.json
        working-directory: test

      - name: Read JSON step output
        run: echo '${{ steps.build.outputs.output }}'

  run:
    name: Skaffold Run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@1.7.0
        with:
          addons: registry

      - name: Setup Helm
        uses: hiberbee/github-action-helm@1.13.0
        with:
          repository-config: test/repositories.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}\

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "{{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run Skaffold pipeline as action
        uses: bennovw/github-action-skaffold@latest
        with:
          command: run
          cache: false
          insecure-registries: localhost:5000
          namespace: default
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          verbosity: info
          working-directory: test

      - name: Run Skaffold with output to file
        uses: bennovw/github-action-skaffold@latest
        with:
          command: build
          file-output: tags.json
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          working-directory: test

      - name: Get Helm releases
        run: helm list
